# Generated by Django 5.2.17 on 2026-09-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project_project_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='feature_one_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='feature_one_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='feature_two_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='feature_two_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
